import { NextRequest, NextResponse } from "next/server";
import * as sql from "mssql";
export const dynamic = "force-dynamic";
import path from "path";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { getServerSession } from "next-auth";
import { DateTime } from 'luxon';
import { authOptions } from "../../auth/[...nextauth]/options";
import { getConnection } from "@/lib/dbConnect";
import { signOut } from "next-auth/react";

function sanitizeInput(obj: any) {
    if (typeof obj !== "object" || obj === null) return obj;

    for (const key of Object.keys(obj)) {
        if (
            key === "__proto__" ||
            key === "constructor" ||
            key === "prototype"
        ) {
            throw new Error("Invalid input");
        }
        sanitizeInput(obj[key]);
    }
    return obj;
}

export async function POST(req: NextRequest) {
    const pool = await getConnection();

    if (!pool || !pool.connected) {
        throw new Error("DB Not Connected");
    }

    const session = await getServerSession(authOptions);

    if (!session) {
        await signOut({ callbackUrl: '/sign-in', redirect: true })
        return NextResponse.json("Invalid Request")
    }

    var EmpCode = "", EmpName = "", WMSDept = ''
    if (session) {
        EmpCode = session?.user?.id || "";
        EmpName = session?.user?.username || "";
        WMSDept = session.user.WMSDept || ""
    }

    const res = await fetch("https://jajitapps.jindalstainless.com:9234/api/Auth/login", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: JSON.stringify(
            {
                "ccmsUser": process.env.NEXT_PUBLIC_Token_CCMSUser,
                "password": process.env.NEXT_PUBLIC_Token_Password,
                "regiKey": process.env.NEXT_PUBLIC_Token_RegiKey,
                "appId": process.env.NEXT_PUBLIC_Token_AppId,
            })
    });

    const data = await res.json();

    // console.log(data)

    try {

        const body = await req.json();
        // const body = sanitizeInput(rawbody);

        // const body = await req.json();
        const DisposerID = body.disposer
        const Quantity = body.quantity
        const MUID = body.unitId
        const Waste = body.selectedWaste

        // console.log(body)
        // console.log(EmpCode, EmpName)
        // if (SegLeadEmpCode) return NextResponse.json("No Employee Code")

        const getSenderMail = await pool
            .request()
            .input("FLAG", "EMP-DTLS-BY-CODE")
            .input("EmpCode", EmpCode)
            .execute("PRO-WMS_GET")

        const sender = await getSenderMail.recordset
        const senderMail = sender[0].EMAIL
        // console.log(sender)


        const CCMails = [senderMail];
        const CCEmails = CCMails.join(",")


        const getDisposerRes = await pool
            .request()
            .input("FLAG", "GetMailofDisposers")
            .input("DeptID", DisposerID)
            .execute("PRO-WMS_GET")

        const disposers = await getDisposerRes.recordset

        const disposerMails = disposers.map((el) => el.EMAIL).join(",")
        const toEmail = disposerMails

        // const disposerMails = [senderMail];
        // const CCEmails = CCMails.join(",")
        // console.log(disposers, DisposerID, disposerMails)




        const now = new Date();
        const generatedOn = DateTime.now()
            .setZone('Asia/Kolkata')
            .toFormat('dd/MM/yyyy HH:mm');


        const mailBody = `
        <p>Dear Waste Approver,</p>

        <p>A new waste record has been generated and is awaiting your review and approval.</p>

        <p><strong>Waste Details:</strong></p>
        <ul>
          <li>Waste : ${Waste}</li>
          <li>Quantity : ${Quantity}${MUID == 2 ? " KG" : " No."}</li>
          <li>Generated By : ${EmpName} (${WMSDept})</li>
          <li>Generated On : ${generatedOn}</li>
        </ul>

        <p>Please log in to the Waste Management System to review the generated waste and take necessary action.</p>
        <a href="https://jslaisrv01.jindalstainless.com:4433"> WMS </a>



        <p>If you experience any technical difficulties accessing the portal, feel free to reach out to the Environment team.</p>

        <p>Thank you for your prompt attention.</p>

        <p>
        Regards,<br/>
        WMS Team<br/>
        Jindal Stainless Limited
        `

        const sendMail = await fetch(`https://jajitapps.jindalstainless.com:9234/api/AutoEmail/InstantEmailSend`, {
            method: "POST",
            headers: {
                'Authorization': `Bearer ${data.token}`,
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                "subject": `WMS : New Waste Generated_Action Required_${Waste}`,
                "emailBody": mailBody,
                "fromEmail": "no-reply@jindalstainless.com",
                "fromName": "WMS",
                "toEmail": toEmail,
                "ccEmail": CCEmails,
                "bccEmail": "aditya_mishra@jindalstainless.com,abhishek.silawat@jindalstainless.com"
            })
        });
        // console.log(await response)
        const mailSent = await sendMail.json()
        // console.log(mailSent)
        return NextResponse.json({ mailSent })

        // return new Response(JSON.stringify(result.recordset), { status: 200 });

    }
    catch (err) {
        return NextResponse.json(
            { error: "Bad request" },
            { status: 400 }
        );
    }
} 